version: 1.0.{build}
configuration: Debug
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
build:
  verbosity: minimal
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: MZT8wlC8wdXHWX6/63F/UmqElo4hDKvlN8oII33ROwLcAo+tZE3Uzq8mzm2eGITj
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
